//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunden har tagits bort..
        /// </summary>
        internal static string Action_Member_Deleted {
            get {
                return ResourceManager.GetString("Action_Member_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunden har sparats..
        /// </summary>
        internal static string Action_Member_Saved {
            get {
                return ResourceManager.GetString("Action_Member_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktuppgiften har tagits bort..
        /// </summary>
        internal static string Action_Post_Deleted {
            get {
                return ResourceManager.GetString("Action_Post_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktuppgiften har sparats..
        /// </summary>
        internal static string Action_Post_Saved {
            get {
                return ResourceManager.GetString("Action_Post_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okänd händelse..
        /// </summary>
        internal static string Action_Unknown {
            get {
                return ResourceManager.GetString("Action_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kunden.
        /// </summary>
        internal static string Data_Type_Member {
            get {
                return ResourceManager.GetString("Data_Type_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kontaktuppgiften.
        /// </summary>
        internal static string Data_Type_Post {
            get {
                return ResourceManager.GetString("Data_Type_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffade i dataåtkomstlagret..
        /// </summary>
        internal static string Generic_DAL_Error_Message {
            get {
                return ResourceManager.GetString("Generic_DAL_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Member_ {
            get {
                return ResourceManager.GetString("Member_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker på att du vill ta bort &apos;{0}&apos;?.
        /// </summary>
        internal static string Member_Delete_Confirm {
            get {
                return ResourceManager.GetString("Member_Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffade då kunden skulle tas bort..
        /// </summary>
        internal static string Member_Deleting_Error {
            get {
                return ResourceManager.GetString("Member_Deleting_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid emailaddress..
        /// </summary>
        internal static string Member_Mail_Invalid_Format {
            get {
                return ResourceManager.GetString("Member_Mail_Invalid_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your emailaddress is too long. Is this really correct?.
        /// </summary>
        internal static string Member_Mail_MaxLength {
            get {
                return ResourceManager.GetString("Member_Mail_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your emailddress..
        /// </summary>
        internal static string Member_Mail_Required {
            get {
                return ResourceManager.GetString("Member_Mail_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name can contain at a maximum 30 characters..
        /// </summary>
        internal static string Member_Name_MaxLength {
            get {
                return ResourceManager.GetString("Member_Name_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your name..
        /// </summary>
        internal static string Member_Name_Required {
            get {
                return ResourceManager.GetString("Member_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password can contain at a minimum 20 characters..
        /// </summary>
        internal static string Member_Password_MaxLength {
            get {
                return ResourceManager.GetString("Member_Password_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password..
        /// </summary>
        internal static string Member_Password_Required {
            get {
                return ResourceManager.GetString("Member_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffade då kunden skulle sparas..
        /// </summary>
        internal static string Member_Saving_Error {
            get {
                return ResourceManager.GetString("Member_Saving_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length - 30 characters..
        /// </summary>
        internal static string Member_Username_MaxLength {
            get {
                return ResourceManager.GetString("Member_Username_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username must contain something..
        /// </summary>
        internal static string Member_Username_Required {
            get {
                return ResourceManager.GetString("Member_Username_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while deleting the post..
        /// </summary>
        internal static string Post_Deleting_Error {
            get {
                return ResourceManager.GetString("Post_Deleting_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while inserting the post..
        /// </summary>
        internal static string Post_Inserting_Error {
            get {
                return ResourceManager.GetString("Post_Inserting_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured while inserting the post..
        /// </summary>
        internal static string Post_Inserting_Unexpected_Error {
            get {
                return ResourceManager.GetString("Post_Inserting_Unexpected_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while selecting the post..
        /// </summary>
        internal static string Post_Selecting_Error {
            get {
                return ResourceManager.GetString("Post_Selecting_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while updating the post..
        /// </summary>
        internal static string Post_Updating_Error {
            get {
                return ResourceManager.GetString("Post_Updating_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured while updating the post..
        /// </summary>
        internal static string Post_Updating_Unexpected_Error {
            get {
                return ResourceManager.GetString("Post_Updating_Unexpected_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktinformationen kan bestå av som mest 50 tecken..
        /// </summary>
        internal static string Post_Value_MaxLength {
            get {
                return ResourceManager.GetString("Post_Value_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a post..
        /// </summary>
        internal static string Post_Value_Required {
            get {
                return ResourceManager.GetString("Post_Value_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[a-zA-Z0-9.!#$%&amp;&apos;*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$.
        /// </summary>
        internal static string Regular_Expression_Mail {
            get {
                return ResourceManager.GetString("Regular_Expression_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel inträffade. Korrigera det som är fel och försök igen..
        /// </summary>
        internal static string Validation_Header {
            get {
                return ResourceManager.GetString("Validation_Header", resourceCulture);
            }
        }
    }
}
